### ISSUE TITLE
Google Translate API Key needed for further translation

### ISSUE THREAD

**Issue by elspru** [elspru/spel#4]
Currently the word list can't grow anymore, because there are no more "Free translations" available. 
So a google API key is necessary to add new words and translations for them. 
A google API key costs $20USD for a million characters, or roughly 6,000 words if each is translated to 26 languages. 
Once the words are translated the first time, they are kept on file, so will always be available in future.

**Comment by kheifer** [comment]
So are you basically asking for someone to purchase a google API key for this project?

**Comment by elspru** [comment]
Hi Kheifer yes, but fortunately I've managed to find a workaround. 
I was going to go ahead and pay for it, but when I signed up to google services I found out that they have a two month free trial with first $300 free. So i've been busy translating as much as possible. 
Already have around 40 thousand words in 22 languages. My current scripts use the most popular 37 languages so I'm on track to having it fully fleshed out by the end of the trial. 

Thanks for asking.
